### ISSUE TITLE
Impossible to run cpu-vs-cpu

### ISSUE THREAD

**Issue by damianski794** [alxdrcirilo/Hex#1]
I've set values like this:
![image](https://user-images.githubusercontent.com/33297451/120906626-537da980-c65b-11eb-93c7-6ac6d690731c.png)

When I run a program, then I get an error:
![image](https://user-images.githubusercontent.com/33297451/120906644-73ad6880-c65b-11eb-948f-2db45dd69e9d.png)

Have you tested cpu-vs-cpu games?

**Comment by alxdrcirilo** [comment]
Comment out line 119 and enable lines 122-123 from the **logic.py** file. By doing this, you will allow MCTS to run on the blue player and disable the interactive mode. Let me know if that works.

**Comment by damianski794** [comment]
Yes, it solves the problem. Sometimes "division by zero error" occurs latter but it is an easy fix  - just instead of dividing by zero we can set dividing by (zero  + very small epsilon)
